services:
  user_service:
    build: ./userService
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  order_service:
    build: ./orderService
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
